version: "3"

services:
  app:
    container_name: gpt-ai-assistant
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"

  webserver:
    image: nginx:1.23.3
    # volumes:
    #  - ./sites-enabled/:/etc/nginx/conf.d/
    depends_on:
    - app
    ports:
    - 80:80
    # - 443:443
    restart: always
    volumes:
      - ./sites-enabled/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www:/var/www/certbot/:ro
  #     - ./certbot/conf/:/etc/nginx/ssl/:ro
  # certbot:
  #     image: certbot/certbot:latest
  #     volumes:
  #       - ./certbot/www/:/var/www/certbot/
  #       - ./certbot/conf/:/etc/letsencrypt/
  #     ports:
  #       - 80:80

