version: "3"

services:
  api-server:
    image: api-server
    ports:
      - 5000:5000
    volumes:
      - ./mongo_db_demo/server/db:/usr/src/app/db
      - ./mongo_db_demo/server/models:/usr/src/app/models
      - ./mongo_db_demo/server/controllers:/usr/src/app/controllers
      - ./mongo_db_demo/server/routes:/usr/src/app/routes
      - ./mongo_db_demo/server/index.js:/usr/src/app/index.js
    depends_on:
      - standalone
  standalone:
    image: mongo:6.0.3
    ports: 
      - 27017:27017
    command: mongod --dbpath /data/db --port 27017 --config /resource/mongod.yml
    volumes:
      - ./standalone/config/mongod.yml:/resource/mongod.yml
      - ./standalone/data:/data/db

  app:
    container_name: gpt-ai-assistant
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=michael@2beasy.com.tw
    # env_file:
    #   - ./nginx-certbot.env
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./sites-enabled:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:

  # webserver:
  #   image: nginx:1.23.3
  #   # volumes:
  #   #  - ./sites-enabled/:/etc/nginx/conf.d/
  #   depends_on:
  #   - app
  #   ports:
  #   - 80:80
  #   # - 443:443
  #   restart: always
  #   volumes:
  #     - ./sites-enabled/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www:/var/www/certbot/:ro
  #     - ./certbot/conf/:/etc/nginx/ssl/:ro
  # certbot:
  #     image: certbot/certbot:latest
  #     volumes:
  #       - ./certbot/www/:/var/www/certbot/
  #       - ./certbot/conf/:/etc/letsencrypt/
  #     ports:
  #       - 80:80

